language: python
python:
  - 3.5
  - 3.6
  - nightly

# command to install dependencies
install:
  - pip install -r requirements.txt
  - python3 setup.py install

# command to run tests
script: ./smoke-test.sh
