#!/bin/bash
CMD=`basename $0`

out="$HOME/sandbox/vvote.wiki/usage.org"
date > $out

cat >> $out <<EOF
* About this document
This file was automatically generated by $CMD.  It lists the programs
available though ~vvote~ and brief usage help for each.

EOF

for prog in countvote sovc lvr transpose genmap xls2csv compare
do
    echo "* $prog" >> $out
    $prog --help   >> $out
done

echo "Write file: $out"
